try{
    console.log(naoExisto);
}catch(err){
    console.log('naoExito n√£o foi declarado')
}